version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis-bucket
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  redis_data: